graphhopper:
  graph.flag_encoders: car
  prepare.ch.weightings: fastest
  prepare.ch.edge_based: off
  prepare.min_network_size: 200
  prepare.min_one_way_network_size: 200
  routing.non_ch.max_waypoint_distance: 1000000

  graph.dataaccess: RAM_STORE

server:
  applicationConnectors:
  - type: http
    port: 8989
    bindHost: 192.168.0.104
  requestLog:
      appenders: []
  adminConnectors:
  - type: http
    port: 8990
    bindHost: 192.168.0.104

logging:
  appenders:
  - type: file
    timeZone: UTC
    currentLogFilename: logs/graphhopper.log
    logFormat: "%d{YYYY-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    archive: true
    archivedLogFilenamePattern: ./logs/graphhopper-%d.log.gz
    archivedFileCount: 30
    neverBlock: true
  - type: console
    timeZone: UTC
    logFormat: "%d{YYYY-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
